# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Grabbit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Grabbit
  pod 'GoogleSignIn'
  pod 'GoogleSignInSwiftSupport'
  pod 'Firebase'
  pod 'FirebaseAuth'
  pod 'FirebaseMessaging'
  pod 'Alamofire'

end
